name: Run Pytest on Push

on:
  push:
    branches:
      - master
      - main
      - develop
      - feature/*

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Lint code with Ruff
        run: uvx ruff check --output-format=github --target-version=py313

      - name: Check code formatting with Ruff
        run: uvx ruff format --diff --target-version=py313
        continue-on-error: true

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: uv run pytest tests
